/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modele.element;

import canvas.SpriteSheet;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ssj-m_000
 */
public class CombatGraphique2 extends javax.swing.JPanel {
private Aventure aventure;
    /**
     * Creates new form CombatGraphique2
     */
    public CombatGraphique2(){
        initComponents();
        miseAJourComposants();
    }
    public void bindAventure(Aventure a) {
        this.aventure = aventure;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEnnemi = new javax.swing.JPanel();
        VieHeroBar = new javax.swing.JProgressBar();
        VieHeroText = new javax.swing.JTextField();
        PanelHero = new javax.swing.JPanel();
        VieEnnemiBar = new javax.swing.JProgressBar();
        VieEnnemiText = new javax.swing.JTextField();
        PanelOptionsHero = new javax.swing.JPanel();
        InventaireBoutton = new javax.swing.JButton();
        AttaqueBoutton = new javax.swing.JButton();
        FuiteBoutton = new javax.swing.JButton();
        DessinEnnemi = new canvas.Canvas();
        DessinHero = new canvas.Canvas();

        VieHeroText.setText("jTextField2");

        javax.swing.GroupLayout PanelEnnemiLayout = new javax.swing.GroupLayout(PanelEnnemi);
        PanelEnnemi.setLayout(PanelEnnemiLayout);
        PanelEnnemiLayout.setHorizontalGroup(
            PanelEnnemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnnemiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEnnemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VieHeroBar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEnnemiLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(VieHeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelEnnemiLayout.setVerticalGroup(
            PanelEnnemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEnnemiLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(VieHeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VieHeroBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        VieEnnemiText.setText("jTextField1");

        javax.swing.GroupLayout PanelHeroLayout = new javax.swing.GroupLayout(PanelHero);
        PanelHero.setLayout(PanelHeroLayout);
        PanelHeroLayout.setHorizontalGroup(
            PanelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VieEnnemiBar, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VieEnnemiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelHeroLayout.setVerticalGroup(
            PanelHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(VieEnnemiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VieEnnemiBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InventaireBoutton.setText("Inventaire");
        InventaireBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventaireBouttonActionPerformed(evt);
            }
        });

        AttaqueBoutton.setText("Attaque");
        AttaqueBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttaqueBouttonActionPerformed(evt);
            }
        });

        FuiteBoutton.setText("Fuir");
        FuiteBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuiteBouttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOptionsHeroLayout = new javax.swing.GroupLayout(PanelOptionsHero);
        PanelOptionsHero.setLayout(PanelOptionsHeroLayout);
        PanelOptionsHeroLayout.setHorizontalGroup(
            PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AttaqueBoutton)
                .addGap(18, 18, 18)
                .addComponent(InventaireBoutton)
                .addGap(18, 18, 18)
                .addComponent(FuiteBoutton)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        PanelOptionsHeroLayout.setVerticalGroup(
            PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuiteBoutton)
                    .addComponent(AttaqueBoutton)
                    .addComponent(InventaireBoutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DessinEnnemiLayout = new javax.swing.GroupLayout(DessinEnnemi);
        DessinEnnemi.setLayout(DessinEnnemiLayout);
        DessinEnnemiLayout.setHorizontalGroup(
            DessinEnnemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        DessinEnnemiLayout.setVerticalGroup(
            DessinEnnemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DessinHeroLayout = new javax.swing.GroupLayout(DessinHero);
        DessinHero.setLayout(DessinHeroLayout);
        DessinHeroLayout.setHorizontalGroup(
            DessinHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        DessinHeroLayout.setVerticalGroup(
            DessinHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(DessinHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(PanelEnnemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(DessinEnnemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(PanelOptionsHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DessinHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DessinEnnemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelEnnemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addComponent(PanelOptionsHero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InventaireBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventaireBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventaireBouttonActionPerformed

    private void AttaqueBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttaqueBouttonActionPerformed
        aventure.getJoueur().setProperty("pv", 50);
        miseAJourComposants();
    }//GEN-LAST:event_AttaqueBouttonActionPerformed

    private void FuiteBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuiteBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuiteBouttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttaqueBoutton;
    private canvas.Canvas DessinEnnemi;
    private canvas.Canvas DessinHero;
    private javax.swing.JButton FuiteBoutton;
    private javax.swing.JButton InventaireBoutton;
    private javax.swing.JPanel PanelEnnemi;
    private javax.swing.JPanel PanelHero;
    private javax.swing.JPanel PanelOptionsHero;
    private javax.swing.JProgressBar VieEnnemiBar;
    private javax.swing.JTextField VieEnnemiText;
    private javax.swing.JProgressBar VieHeroBar;
    private javax.swing.JTextField VieHeroText;
    // End of variables declaration//GEN-END:variables

     private void miseAJourComposants() {
        VieHeroBar.setMaximum((int)this.aventure.getJoueur().getAjoute("pv max"));
        VieHeroBar.setValue((int)this.aventure.getJoueur().getAjoute("pv"));
        VieHeroText.setText(this.aventure.getJoueur().getAjoute("pv") + "/" + this.aventure.getJoueur().getAjoute("pv max"));
        
        VieEnnemiBar.setMaximum((int)this.aventure.getJoueur().getAjoute("pv max"));
        VieEnnemiBar.setValue((int)this.aventure.getJoueur().getAjoute("pv"));
        VieEnnemiText.setText(this.aventure.getJoueur().getAjoute("pv") + "/" + this.aventure.getJoueur().getAjoute("pv max"));
        
        
        SpriteSheet sprite = new SpriteSheet("/HerosSpriteSheet.png",0,0,64,64,64*3,64*3);
        sprite.loadImage();
        DessinHero.ajouterItem(sprite);
        //DessinHero.(s);
        
        
        new Timer("Drawer", true).scheduleAtFixedRate( new TimerTask(){
            public void run(){
               
               DessinEnnemi.repaint();
               DessinHero.repaint();
               //DessinEnnemi.ajouterItem(sprite);
               //DessinHero.ajouterItem(sprite);

            }
        }, 
        100, // Start in 100 ms
        (int)(1000 / 60));
        
        
    }
}
