/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canvas.Combat;

import canvas.SpriteSheet;
import javax.swing.DefaultListModel;
import modele.element.Aventure;
import modele.element.Effet;
import modele.element.Equipement;
import modele.element.Objet;
import modele.element.Personnage;
import modele.element.PropertyList;

/**
 *
 * @author ssj-m_000
 */
public class CombatGraphique2 extends javax.swing.JPanel {
private Aventure aventure;
private Personnage Moi;
private Personnage Ennemi;
    /**
     * Creates new form CombatGraphique2
     */
    public CombatGraphique2(){
        initComponents();
        jPanel3.setVisible(false);
    }
    public void bindAventure(Aventure a) {
        this.aventure = a;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPaneInventaire = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        listeObjetInventaire = new javax.swing.JList<>();
        utiliserBouton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelOptionsHero = new javax.swing.JPanel();
        InventaireBoutton = new javax.swing.JButton();
        AttaqueBoutton = new javax.swing.JButton();
        FuiteBoutton = new javax.swing.JButton();
        jScrollPane23 = new javax.swing.JScrollPane();
        listeEffetJoueur = new javax.swing.JList<>();
        combatGraphiqueContainerPersonnage1 = new canvas.Combat.CombatGraphiqueContainerPersonnage();
        combatGraphiqueContainerPersonnage2 = new canvas.Combat.CombatGraphiqueContainerPersonnage();

        setBackground(new java.awt.Color(28, 17, 23));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jTextPaneInventaire.setEditable(false);
        jTextPaneInventaire.setText("Inventaire:");
        jScrollPane19.setViewportView(jTextPaneInventaire);

        jScrollPane20.setViewportView(listeObjetInventaire);

        utiliserBouton.setText("Utiliser");
        utiliserBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utiliserBoutonActionPerformed(evt);
            }
        });

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane19)
            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utiliserBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utiliserBouton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        PanelOptionsHero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        InventaireBoutton.setText("Inventaire");
        InventaireBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventaireBouttonActionPerformed(evt);
            }
        });

        AttaqueBoutton.setText("Attaque");
        AttaqueBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttaqueBouttonActionPerformed(evt);
            }
        });

        FuiteBoutton.setText("Fuir");
        FuiteBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuiteBouttonActionPerformed(evt);
            }
        });

        jScrollPane23.setViewportView(listeEffetJoueur);

        javax.swing.GroupLayout PanelOptionsHeroLayout = new javax.swing.GroupLayout(PanelOptionsHero);
        PanelOptionsHero.setLayout(PanelOptionsHeroLayout);
        PanelOptionsHeroLayout.setHorizontalGroup(
            PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AttaqueBoutton)
                .addGap(18, 18, 18)
                .addComponent(InventaireBoutton)
                .addGap(18, 18, 18)
                .addComponent(FuiteBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        PanelOptionsHeroLayout.setVerticalGroup(
            PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionsHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuiteBoutton)
                    .addComponent(AttaqueBoutton)
                    .addComponent(InventaireBoutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelOptionsHeroLayout.createSequentialGroup()
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelOptionsHero, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelOptionsHero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(combatGraphiqueContainerPersonnage1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(combatGraphiqueContainerPersonnage2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combatGraphiqueContainerPersonnage2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(combatGraphiqueContainerPersonnage1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InventaireBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventaireBouttonActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_InventaireBouttonActionPerformed

    private void AttaqueBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttaqueBouttonActionPerformed
        System.out.println(this.Moi.attaque(this.Ennemi));
        System.out.println(Ennemi.attaque(this.Moi));
        this.Moi.actionEffetFinDuTour();
        this.Ennemi.actionEffetFinDuTour();
        if(this.Moi.getAjoute("pv") <= 0 || this.Ennemi.getAjoute("pv") <= 0){
            this.aventure.finCombat(Moi,Ennemi);
        }
        miseAJourComposants();
    }//GEN-LAST:event_AttaqueBouttonActionPerformed

    private void FuiteBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuiteBouttonActionPerformed
        if(this.Moi.essaiEnfuir(this.Ennemi)){
            this.aventure.finCombat(Moi,Ennemi);
        }else if (!Ennemi.isDead()) {
            Ennemi.attaque(this.Moi);
        }
        this.Moi.actionEffetFinDuTour();
        this.Ennemi.actionEffetFinDuTour();
        miseAJourComposants();
    }//GEN-LAST:event_FuiteBouttonActionPerformed

    private void utiliserBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utiliserBoutonActionPerformed
        int selected = listeObjetInventaire.getSelectedIndex();
        Objet obj = listeObjetInventaire.getSelectedValue();
        if (obj == null) return;

        boolean needUpdate = false;

        if (obj instanceof Equipement) {
            if (this.aventure.getJoueur().getMain()==obj || this.aventure.getJoueur().getArmure()==obj) {
                needUpdate = this.aventure.getJoueur().desequip(selected);
            } else {
                needUpdate = this.aventure.getJoueur().equip(selected);
            }
        } else if (obj.peutUtiliser()) {
            needUpdate = this.aventure.getJoueur().utiliserObjet(selected);
        }

        if (needUpdate) {
            miseAJourComposants();
        }
    }//GEN-LAST:event_utiliserBoutonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttaqueBoutton;
    private javax.swing.JButton FuiteBoutton;
    private javax.swing.JButton InventaireBoutton;
    private javax.swing.JPanel PanelOptionsHero;
    private canvas.Combat.CombatGraphiqueContainerPersonnage combatGraphiqueContainerPersonnage1;
    private canvas.Combat.CombatGraphiqueContainerPersonnage combatGraphiqueContainerPersonnage2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JTextPane jTextPaneInventaire;
    private javax.swing.JList<Effet> listeEffetJoueur;
    private javax.swing.JList<Objet> listeObjetInventaire;
    private javax.swing.JButton utiliserBouton;
    // End of variables declaration//GEN-END:variables

    private void miseAJourComposants() {
        //VieHeroBar.setMaximum((int)this.Moi.getAjoute("pv max"));
        //VieHeroBar.setValue((int)this.Moi.getAjoute("pv"));
        //VieHeroText.setText(this.Moi.getAjoute("pv") + "/" + this.Moi.getAjoute("pv max"));
        //NomHeroText.setText(this.Moi.getNom());
        
        //VieEnnemiBar.setMaximum((int)this.Ennemi.getAjoute("pv max"));
        //VieEnnemiBar.setValue((int)this.Ennemi.getAjoute("pv"));
        //VieEnnemiText.setText(this.Ennemi.getAjoute("pv") + "/" + this.Ennemi.getAjoute("pv max"));
        //NomEnnemiText.setText(this.Ennemi.getNom());
        //DessinHero.(s);
        
        combatGraphiqueContainerPersonnage1.miseAJour();
        combatGraphiqueContainerPersonnage2.miseAJour();
        
        mettreAJourListeInventaire();
        mettreAJourListeEffet();
    }

    public void mettreAJourCanvas() {
        //DessinEnnemi.repaint();
        //DessinHero.repaint();
        combatGraphiqueContainerPersonnage1.redessiner();
        combatGraphiqueContainerPersonnage2.redessiner();
    }

    public void lancerCombat(Personnage perso1, Personnage perso2) {
        System.out.println(perso1+ " versus " + perso2);
        this.Moi = perso1;
        this.Ennemi = perso2;
        combatGraphiqueContainerPersonnage1.bind(perso1);
        combatGraphiqueContainerPersonnage2.bind(perso2);
        miseAJourComposants();
    }
    
    private void mettreAJourListeInventaire(){
        DefaultListModel<Objet> g = new DefaultListModel<>();
        g.addAll(this.aventure.getJoueur().getInventaire());
        listeObjetInventaire.setModel(g);
        jTextPaneInventaire.setText("Inventaire (" + this.aventure.getJoueur().getPoidsInventaire() + "/" + this.aventure.getJoueur().getAjoute(PropertyList.POIDSMAX)+")");
    }
    private void mettreAJourListeEffet(){
        DefaultListModel<Effet> g = new DefaultListModel<>();
        g.addAll(this.aventure.getJoueur().getEffetCourant());
        listeEffetJoueur.setModel(g);
    }
}
